name: Makefile CI

on:
  push:
    branches: [ "master" ]  # Changed from "master" to "main" if your default branch is "main".
  pull_request:
    branches: [ "master" ]  # Same change as above.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Ensures the latest version of checkout is used.

    - name: Set execute permission for config.sh
      run: chmod +x ./config/config.sh

    - name: Run config script
      run: ./config/config.sh
    - name: Install dependencies
      run: make dependencies  # Assuming you have a 'dependencies' target in your Makefile; otherwise, keep 'make' if it's configured to handle dependencies.

    - name: Run check
      run: make check  # Ensure the 'check' target exists in your Makefile.

    - name: Run distcheck
      run: make distcheck  # Ensure the 'distcheck' target exists in your Makefile.
